repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: make format
        language: system
        types: [python]
        pass_filenames: false

      - id: lint
        name: lint
        entry: make lint
        language: system
        types: [python]
        pass_filenames: false
