services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=fastapi_starter
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./mongodb_data:/data/db
